---
  - name: Install Java 1.8
    yum: name=java-1.8.0-openjdk state=present

  - name: add group "tomcat"
    group: name=tomcat

  - name: add user "tomcat"
    user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
    

  - name: Download Tomcat
    get_url: url=https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.73/bin/apache-tomcat-8.5.73.tar.gz dest=/opt/

  - name: Extract archive
    command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.73.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.73

  - name: Symlink install directory
    file: src=/opt/apache-tomcat-8.5.73 path=/usr/share/tomcat state=link

  - name: Change ownership of Tomcat installation
    file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

  - name: deploy tomcat service file
    template: src=tomcat.service.j2 dest=/etc/systemd/system/tomcat.service
  
  - name: restart daemon
    command: systemctl daemon-reload
  
  - name: start tomcat serverr
    service: name=tomcat state=started
