---
- name: Deploying Web application to Tomcat
  hosts: DEV
  become: true
  tasks:
    - name: Status of tomcat
      shell: "ps -ef | grep 'java'"
      register: tomStatus

    - debug:
        msg: tomcat is running plese stop it
      when: "'tomcat9' in tomStatus.stdout"
